# Numpy

### Importing numpy

In [2]:
import numpy as np

### Basic Array creation 

In [3]:
arr = np.array([1,2,3,4])

print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


### Multi-dimensional Array

In [4]:
print(f"1D Array : {np.array([1,2,3,4])}\n")
print(f"2D Array : \n{np.array([[1,2,3,4],[1,2,3,4]])}\n")
print(f"3D Array : \n{np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])}")

1D Array : [1 2 3 4]

2D Array : 
[[1 2 3 4]
 [1 2 3 4]]

3D Array : 
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


### Array generation

In [5]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
arr = np.zeros(6)
print(arr)
arr = np.zeros((6,3))
print(arr)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr = np.ones(6)
print(arr)
arr = np.ones((6,6))
print(arr)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [8]:
#linspace is a function to create a array from a start value to end value and wanter numbers in between (evenly spaced)

arr = np.linspace(1,5,5)
print(arr)

[1. 2. 3. 4. 5.]


In [9]:
# Creating a 5 elements numpy array, and those 5 elements will be random (from 0 to 1).
arr = np.random.rand(5)
print(arr)

# Creating a 5 elements numpy array, and those 5 elements will be random (from 3 to -3). 
arr = np.random.randn(5)
print(arr)

# Creating a 5 elements numpy array, and those 5 elements will be random (start,end,no. of elements). 
arr = np.random.randint(10,20,10)

[0.71600287 0.14595138 0.15350064 0.42421344 0.2405667 ]
[-0.33777958 -0.92928651 -0.52797932  0.17270274 -0.8080791 ]


### Array attributes

In [10]:
arr = np.array([[1,2,3],[1,5,3]])
print(arr)

[[1 2 3]
 [1 5 3]]


In [11]:
print(arr.shape)
print(arr.size)
print(arr.dtype)

(2, 3)
6
int64


### Array method

In [12]:
print(arr.min ()) # <- returns the minimum element of the array
print(arr.max()) # <- returns the maximum element of the array
print(arr.sum()) # <- returns the sum of the array

print(np.sum(arr,axis=0)) # <- returns the sum of all the vertical axis
print(np.sum(arr,axis=1)) # <- returns the sum of all the horizontal axis

print(arr.mean()) # <- returns the mean element of the array (sum of numbers/total numbers)
print(arr.std()) # <- returns the standard deviation of the array

print(arr.argmax()) # <- returns the index number of the max element in the array 
print(arr.argmin()) # <- returns the index number of the min element in the array 

1
5
15
[2 7 6]
[6 9]
2.5
1.3844373104863459
4
0


### Resizing and Reshaping

In [13]:
arr = np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [14]:
arr = arr.reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### Indexing and Slicing

In [15]:
arr = np.arange(1,11)

In [16]:
print(arr[0])
print(arr[0:5])

1
[1 2 3 4 5]


### Matrix Indexing and Slicing

In [17]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [18]:
print(arr[0]) # <- Returns the row of the martix
print(arr[0][0]) # <- returns a number from the 0th row and 0th index of that row


[1 2 3 4 5]
1


In [19]:
slice_ = arr[3:,3:]
print(slice_)

column2 = arr[:,1]
print(column2)

[[19 20]
 [24 25]
 [29 30]]
[ 2  7 12 17 22 27]


### Boolean Indexing

In [20]:
arr = np.arange(0,11)
bool_arr = arr%2 == 0

print(bool_arr)

[ True False  True False  True False  True False  True False  True]


In [21]:
arr = arr[bool_arr]
print(arr)

[ 0  2  4  6  8 10]


### Array Operations

#### Arithmetic operations

In [22]:
# Size must be same of both of the array
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

ans = arr1 + arr2
print(ans)

ans = arr1 - arr2
print(ans)

ans = arr1 / arr2
print(np.round(ans,decimals=2))

ans = arr1 * arr2
print(ans)


ans = arr1 % arr2
print(ans)


ans = arr1 ** arr2
print(ans)

ans = arr1 // arr2
print(ans)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[0.17 0.29 0.38 0.44 0.5 ]
[ 6 14 24 36 50]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]
[0 0 0 0 0]


#### Broadcasting

In [23]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])  

b = np.array([10, 20, 30])

# Broadcasting allows 'b' to be added to each row of 'a'
result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


#### Deep and shallow copy

In [24]:
# Deep copy

a = np.arange(1,21)

b = a

print("'b' is a Deep copy of 'a' \n")

b[0] = 10
print(f"If b's value is changed : (b[0] = 10)\n\n{b}\n\n 'a' will be automatically changed \n\n{a}\n\n")


'b' is a Deep copy of 'a' 

If b's value is changed : (b[0] = 10)

[10  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 'a' will be automatically changed 

[10  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]




In [25]:
# Shallow copy

a = np.arange(1,21)

b = a.copy()

print("'b' is a shallow copy of 'a' \n")

b[0] = 10
print(f"If b's value is changed : (b[0] = 10)\n\n{b}\n\n 'a' will not change \n\n{a}\n\n")


'b' is a shallow copy of 'a' 

If b's value is changed : (b[0] = 10)

[10  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 'a' will not change 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]




#### Matrix operation

##### Dot product

In [26]:
matrix = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(1,5).reshape(2,2)

print(f"{matrix}\n\n")

print(np.dot(matrix,matrix2))  # <- returns the dot product of the matrix

[[1 2]
 [3 4]]


[[ 7 10]
 [15 22]]


##### Transposing matrix

In [27]:
arr = np.arange(1,11).reshape(5,2)

print(arr.T)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


#### Stacking of Array

In [28]:
arr1 = np.arange(1,11)
arr2 = np.arange(1,11)

print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
# verically stacking

v_stack = np.vstack((arr1,arr2))
print(f"{v_stack}\n\n")

# horizontal stacking

h_stack = np.hstack((arr1,arr2))
print(f"{h_stack}\n\n") 

col_stack = np.column_stack((arr1,arr2))
print(f"{col_stack}\n\n")

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


[[ 1  1]
 [ 2  2]
 [ 3  3]
 [ 4  4]
 [ 5  5]
 [ 6  6]
 [ 7  7]
 [ 8  8]
 [ 9  9]
 [10 10]]




#### Splitting of array

In [30]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [31]:
#Horizontal split

h_split = np.hsplit(arr,4)
print(f"{h_split}\n\n")

v_split = np.vsplit(arr,4)
print(f"{v_split}\n\n")

[array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]]), array([[ 4],
       [ 8],
       [12],
       [16]])]


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]




# Questions


In [32]:
# Valid sudoku

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

try:
    s.reshape(9,9)
    if (np.sum(s,axis=1) == 45).all() and (np.sum(s,axis=0) == 45).all():
        pass
    else:
        raise Exception()
    
    print("Valid sudoku")
except Exception as e:
    print("Not a valid sudoku")
    print(e)

Valid sudoku


In [33]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [34]:
#Get the shape of the matrix.

print(f"Shape : {data.shape}")

Shape : (5, 3)


In [35]:
#Find the average age of students.

coulmn = data[:,1]
print(coulmn.sum()/len(coulmn))

81.6
